name: CI Practice

on:
  push:

jobs:
  health:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: start
        run: |
          echo "Workflow has started."
          touch test.txt
          if [ -f "test.txt" ]; then
            echo "File created"
          else
            echo "File doesnot created"
          

      - name: completed
        run: echo "Workflow has completed" 
