name: CI Practice

on:
  push:

jobs:
  health:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: start
        run: |
          echo "Workflow has started."
          touch test.txt
           
      
      - name: Check File Exist
        run: | 
          if [ -f "test.txt" ]; then
            echo "File created"
          else
            echo "File doesnot created"
          fi
      
      - name: Running with Bash
        shell: bash
        run: echo "Running on bash"
        
      - name: Runnig on python
        shell: python
        run: echo "Running on bash"
       
    #  - name: Failure Behavior
    #   run: |
    #     echo "Brfore failure"
    #     cout "fail"
    #     echo "After failure"
 

      - name: completed
        run: echo "Workflow has completed" 
